from commands.effect import proc as effect
from commands.kotobagari import proc as kotobagari
from commands.kuwagata import proc as kuwagata
from commands.kuwagata_img import proc as kuwagata_img
from commands.okuri import proc as okuri
from commands.ping import proc as ping
from commands.raika import proc as raika
from commands.removebg import proc as removebg
from commands.tomb import proc as tomb
from commands.txt2img import proc as txt2img
from commands.uma import proc as uma